local colors = require("settings.colorscheme").get_theme_tb("base_30")

return {
	FFFBorder = { fg = colors.darker_black, bg = colors.darker_black },
	FFFSelected = { fg = colors.blue },
	FFFSelectedActive = { fg = colors.blue, bg = colors.black2 },
	FFFGitStaged = { fg = colors.green },
	FFFGitModified = { fg = colors.yellow },
	FFFGitDeleted = { fg = colors.red },
	FFFGitRenamed = { fg = colors.purple },
	FFFGitUntracked = { fg = colors.green },
	FFFGitIgnored = { fg = colors.grey },
	FFFGitSignStaged = { fg = colors.green },
	FFFGitSignModified = { fg = colors.yellow },
	FFFGitSignDeleted = { fg = colors.red },
	FFFGitSignRenamed = { fg = colors.purple },
	FFFGitSignUntracked = { fg = colors.green },
	FFFGitSignIgnored = { fg = colors.grey },
	FFFGitSignStagedSelected = { fg = colors.green, bg = colors.black2 },
	FFFGitSignModifiedSelected = { fg = colors.yellow, bg = colors.black2 },
	FFFGitSignDeletedSelected = { fg = colors.red, bg = colors.black2 },
	FFFGitSignRenamedSelected = { fg = colors.purple, bg = colors.black2 },
	FFFGitSignUntrackedSelected = { fg = colors.green, bg = colors.black2 },
	FFFGitSignIgnoredSelected = { fg = colors.grey, bg = colors.black2 },
	FFFFileInfoSection = { fg = colors.blue },
	FFFFileInfoSeparator = { fg = colors.grey },
	FFFFileInfoLabel = { fg = colors.grey_fg },
	FFFFileInfoValueDim = { fg = colors.grey },
	FFFFileInfoSize = { fg = colors.yellow },
	FFFFileInfoType = { fg = colors.blue },
	FFFFileInfoPath = { fg = colors.cyan },
	FFFFileInfoScorePos = { fg = colors.green },
	FFFFileInfoScoreNeg = { fg = colors.red },
	FFFFileInfoTotalScore = { fg = colors.yellow, bold = true },
	FFFFileInfoMatchType = { fg = colors.purple, bold = true },
}
