local colors = require("settings.colorscheme").get_theme_tb("base_30")

return {
	SnacksPicker = { fg = colors.white, bg = colors.darker_black },
	SnacksPickerBorder = { fg = colors.darker_black, bg = colors.darker_black },
	SnacksPickerBoxBorder = { fg = colors.darker_black, bg = colors.darker_black },
	SnacksPickerInput = { fg = colors.white, bg = colors.black2 },
	SnacksPickerInputBorder = { fg = colors.black2, bg = colors.black2 },
	SnacksPickerInputTitle = { fg = colors.blue, bg = colors.black2 },
	SnacksPickerList = { fg = colors.white, bg = colors.darker_black },
	SnacksPickerListBorder = { fg = colors.darker_black, bg = colors.darker_black },
	SnacksPickerListCursorLine = { bg = colors.black2 },
	SnacksPickerPreview = { fg = colors.white, bg = colors.black },
	SnacksPickerPreviewBorder = { fg = colors.darker_black, bg = colors.black },
	SnacksPickerPreviewCursorLine = { bg = colors.black2 },
	SnacksPickerTitle = { fg = colors.blue, bg = colors.darker_black },
	SnacksPickerFooter = { fg = colors.grey_fg, bg = colors.darker_black },
	SnacksPickerCursorLine = { bg = colors.black2 },
	SnacksPickerMatch = { fg = colors.blue, bold = true },
	SnacksPickerSearch = { fg = colors.black, bg = colors.blue },
	SnacksPickerPrompt = { fg = colors.blue },
	SnacksPickerInputSearch = { fg = colors.blue, bold = true },
	SnacksPickerSpecial = { fg = colors.purple },
	SnacksPickerLabel = { fg = colors.purple },
	SnacksPickerTotals = { fg = colors.grey_fg },
	SnacksPickerFile = { fg = colors.white },
	SnacksPickerDirectory = { fg = colors.folder_bg },
	SnacksPickerDir = { fg = colors.grey_fg },
	SnacksPickerPathIgnored = { fg = colors.grey },
	SnacksPickerPathHidden = { fg = colors.grey },
	SnacksPickerDimmed = { fg = colors.grey },
	SnacksPickerRow = { fg = colors.green },
	SnacksPickerCol = { fg = colors.yellow },
	SnacksPickerComment = { fg = colors.grey_fg },
	SnacksPickerDesc = { fg = colors.grey_fg },
	SnacksPickerDelim = { fg = colors.grey_fg },
	SnacksPickerSpinner = { fg = colors.blue },
	SnacksPickerSelected = { fg = colors.green },
	SnacksPickerUnselected = { fg = colors.grey },
	SnacksPickerIdx = { fg = colors.yellow },
	SnacksPickerTree = { fg = colors.grey_fg },
	SnacksPickerGitStatusAdded = { fg = colors.green },
	SnacksPickerGitStatusModified = { fg = colors.yellow },
	SnacksPickerGitStatusDeleted = { fg = colors.red },
	SnacksPickerGitStatusRenamed = { fg = colors.purple },
	SnacksPickerGitStatusCopied = { fg = colors.cyan },
	SnacksPickerGitStatusUntracked = { fg = colors.green },
	SnacksPickerGitStatusIgnored = { fg = colors.grey },
	SnacksPickerGitStatusUnmerged = { fg = colors.red },
	SnacksPickerGitStatusStaged = { fg = colors.green },
	SnacksPickerGitBranch = { fg = colors.purple },
	SnacksPickerGitBranchCurrent = { fg = colors.green },
	SnacksPickerGitCommit = { fg = colors.yellow },
	SnacksPickerGitDate = { fg = colors.grey_fg },
	SnacksPickerGitAuthor = { fg = colors.cyan },
	SnacksPickerGitType = { fg = colors.blue },
	SnacksPickerGitScope = { fg = colors.purple },
	SnacksPickerGitIssue = { fg = colors.yellow },
	SnacksPickerGitBreaking = { fg = colors.red, bold = true },
	SnacksPickerPickWin = { fg = colors.black, bg = colors.yellow },
	SnacksPickerPickWinCurrent = { fg = colors.black, bg = colors.blue },
}
